export interface Destination {
  id: number
  name: string
  slug: string
  flag: string
  image: string
  visaType: string
  price: string
  popular: boolean
  region: "Schengen" | "Other"
  documentPath: string
}

export const destinations: Destination[] = [
  {
    id: 1,
    name: "France",
    slug: "france",
    flag: "🇫🇷",
    image: "/images/countries/france.jpg",
    visaType: "Schengen Visa",
    price: "249 AED",
    popular: true,
    region: "Schengen",
    documentPath: "/documents/required-documents-to-apply-for-a-tourist-visa-in-france",
  },
  {
    id: 2,
    name: "Italy",
    slug: "italy",
    flag: "🇮🇹",
    image: "/images/countries/italy.jpg",
    visaType: "Schengen Visa",
    price: "249 AED",
    popular: true,
    region: "Schengen",
    documentPath: "/documents/required-documents-to-apply-for-a-tourist-visa-in-italy",
  },
  {
    id: 3,
    name: "Spain",
    slug: "spain",
    flag: "🇪🇸",
    image: "/images/countries/spain.jpg",
    visaType: "Schengen Visa",
    price: "249 AED",
    popular: true,
    region: "Schengen",
    documentPath: "/documents/required-documents-to-apply-for-a-tourist-visa-in-spain",
  },
  {
    id: 4,
    name: "Germany",
    slug: "germany",
    flag: "🇩🇪",
    image: "/images/countries/germany.jpg",
    visaType: "Schengen Visa",
    price: "249 AED",
    popular: true,
    region: "Schengen",
    documentPath: "/documents/required-documents-to-apply-for-a-tourist-visa-in-germany",
  },
  {
    id: 5,
    name: "Switzerland",
    slug: "switzerland",
    flag: "🇨🇭",
    image: "/images/countries/switzerland.jpg",
    visaType: "Schengen Visa",
    price: "249 AED",
    popular: true,
    region: "Schengen",
    documentPath: "/documents/required-documents-to-apply-for-a-tourist-visa-in-switzerland",
  },
  {
    id: 6,
    name: "Greece",
    slug: "greece",
    flag: "🇬🇷",
    image: "/images/countries/greece.jpg",
    visaType: "Schengen Visa",
    price: "249 AED",
    popular: false,
    region: "Schengen",
    documentPath: "/documents/required-documents-to-apply-for-a-tourist-visa-in-greece",
  },
  {
    id: 7,
    name: "Netherlands",
    slug: "netherlands",
    flag: "🇳🇱",
    image: "/images/countries/netherlands.jpg",
    visaType: "Schengen Visa",
    price: "249 AED",
    popular: false,
    region: "Schengen",
    documentPath: "/documents/required-documents-to-apply-for-a-tourist-visa-in-netherlands",
  },
  {
    id: 8,
    name: "Austria",
    slug: "austria",
    flag: "🇦🇹",
    image: "/images/countries/austria.jpg",
    visaType: "Schengen Visa",
    price: "249 AED",
    popular: false,
    region: "Schengen",
    documentPath: "/documents/required-documents-to-apply-for-a-tourist-visa-in-austria",
  },
  {
    id: 9,
    name: "Belgium",
    slug: "belgium",
    flag: "🇧🇪",
    image: "/images/countries/belgium.jpg",
    visaType: "Schengen Visa",
    price: "249 AED",
    popular: false,
    region: "Schengen",
    documentPath: "/documents/required-documents-to-apply-for-a-tourist-visa-in-belgium",
  },
  {
    id: 10,
    name: "Bulgaria",
    slug: "bulgaria",
    flag: "🇧🇬",
    image: "/images/countries/bulgaria.jpg",
    visaType: "Schengen Visa",
    price: "249 AED",
    popular: false,
    region: "Schengen",
    documentPath: "/documents/required-documents-to-apply-for-a-tourist-visa-in-bulgaria",
  },
  {
    id: 11,
    name: "Croatia",
    slug: "croatia",
    flag: "🇭🇷",
    image: "/images/countries/croatia.jpg",
    visaType: "Schengen Visa",
    price: "249 AED",
    popular: false,
    region: "Schengen",
    documentPath: "/documents/required-documents-to-apply-for-a-tourist-visa-in-croatia",
  },
  {
    id: 12,
    name: "Czech Republic",
    slug: "czech-republic",
    flag: "🇨🇿",
    image: "/images/countries/czech-republic.jpg",
    visaType: "Schengen Visa",
    price: "249 AED",
    popular: false,
    region: "Schengen",
    documentPath: "/documents/required-documents-to-apply-for-a-tourist-visa-in-czech-republic",
  },
  {
    id: 13,
    name: "Denmark",
    slug: "denmark",
    flag: "🇩🇰",
    image: "/images/countries/denmark.jpg",
    visaType: "Schengen Visa",
    price: "249 AED",
    popular: false,
    region: "Schengen",
    documentPath: "/documents/required-documents-to-apply-for-a-tourist-visa-in-denmark",
  },
  {
    id: 14,
    name: "Estonia",
    slug: "estonia",
    flag: "🇪🇪",
    image: "/images/countries/estonia.jpg",
    visaType: "Schengen Visa",
    price: "249 AED",
    popular: false,
    region: "Schengen",
    documentPath: "/documents/required-documents-to-apply-for-a-tourist-visa-in-estonia",
  },
  {
    id: 15,
    name: "Finland",
    slug: "finland",
    flag: "🇫🇮",
    image: "/images/countries/finland.jpg",
    visaType: "Schengen Visa",
    price: "249 AED",
    popular: false,
    region: "Schengen",
    documentPath: "/documents/required-documents-to-apply-for-a-tourist-visa-in-finland",
  },
  {
    id: 16,
    name: "Hungary",
    slug: "hungary",
    flag: "🇭🇺",
    image: "/images/countries/hungary.jpg",
    visaType: "Schengen Visa",
    price: "249 AED",
    popular: false,
    region: "Schengen",
    documentPath: "/documents/required-documents-to-apply-for-a-tourist-visa-in-hungary",
  },
  {
    id: 17,
    name: "Iceland",
    slug: "iceland",
    flag: "🇮🇸",
    image: "/images/countries/iceland.jpg",
    visaType: "Schengen Visa",
    price: "249 AED",
    popular: false,
    region: "Schengen",
    documentPath: "/documents/required-documents-to-apply-for-a-tourist-visa-in-iceland",
  },
  {
    id: 18,
    name: "Latvia",
    slug: "latvia",
    flag: "🇱🇻",
    image: "/images/countries/latvia.jpg",
    visaType: "Schengen Visa",
    price: "249 AED",
    popular: false,
    region: "Schengen",
    documentPath: "/documents/required-documents-to-apply-for-a-tourist-visa-in-latvia",
  },
  {
    id: 19,
    name: "Liechtenstein",
    slug: "liechtenstein",
    flag: "🇱🇮",
    image: "/images/countries/liechtenstein.jpg",
    visaType: "Schengen Visa",
    price: "249 AED",
    popular: false,
    region: "Schengen",
    documentPath: "/documents/required-documents-to-apply-for-a-tourist-visa-in-liechtenstein",
  },
  {
    id: 20,
    name: "Lithuania",
    slug: "lithuania",
    flag: "🇱🇹",
    image: "/images/countries/lithuania.jpg",
    visaType: "Schengen Visa",
    price: "249 AED",
    popular: false,
    region: "Schengen",
    documentPath: "/documents/required-documents-to-apply-for-a-tourist-visa-in-lithuania",
  },
  {
    id: 21,
    name: "Luxembourg",
    slug: "luxembourg",
    flag: "🇱🇺",
    image: "/images/countries/luxembourg.jpg",
    visaType: "Schengen Visa",
    price: "249 AED",
    popular: false,
    region: "Schengen",
    documentPath: "/documents/required-documents-to-apply-for-a-tourist-visa-in-luxembourg",
  },
  {
    id: 22,
    name: "Malta",
    slug: "malta",
    flag: "🇲🇹",
    image: "/images/countries/malta.jpg",
    visaType: "Schengen Visa",
    price: "249 AED",
    popular: false,
    region: "Schengen",
    documentPath: "/documents/required-documents-to-apply-for-a-tourist-visa-in-malta",
  },
  {
    id: 23,
    name: "Norway",
    slug: "norway",
    flag: "🇳🇴",
    image: "/images/countries/norway.jpg",
    visaType: "Schengen Visa",
    price: "249 AED",
    popular: false,
    region: "Schengen",
    documentPath: "/documents/required-documents-to-apply-for-a-tourist-visa-in-norway",
  },
  {
    id: 24,
    name: "Poland",
    slug: "poland",
    flag: "🇵🇱",
    image: "/images/countries/poland.jpg",
    visaType: "Schengen Visa",
    price: "249 AED",
    popular: false,
    region: "Schengen",
    documentPath: "/documents/required-documents-to-apply-for-a-tourist-visa-in-poland",
  },
  {
    id: 25,
    name: "Portugal",
    slug: "portugal",
    flag: "🇵🇹",
    image: "/images/countries/portugal.jpg",
    visaType: "Schengen Visa",
    price: "249 AED",
    popular: false,
    region: "Schengen",
    documentPath: "/documents/required-documents-to-apply-for-a-tourist-visa-in-portugal",
  },
  {
    id: 26,
    name: "Romania",
    slug: "romania",
    flag: "🇷🇴",
    image: "/images/countries/romania.jpg",
    visaType: "Schengen Visa",
    price: "249 AED",
    popular: false,
    region: "Schengen",
    documentPath: "/documents/required-documents-to-apply-for-a-tourist-visa-in-romania",
  },
  {
    id: 27,
    name: "Slovakia",
    slug: "slovakia",
    flag: "🇸🇰",
    image: "/images/countries/slovakia.jpg",
    visaType: "Schengen Visa",
    price: "249 AED",
    popular: false,
    region: "Schengen",
    documentPath: "/documents/required-documents-to-apply-for-a-tourist-visa-in-slovakia",
  },
  {
    id: 28,
    name: "Slovenia",
    slug: "slovenia",
    flag: "🇸🇮",
    image: "/images/countries/slovenia.jpg",
    visaType: "Schengen Visa",
    price: "249 AED",
    popular: false,
    region: "Schengen",
    documentPath: "/documents/required-documents-to-apply-for-a-tourist-visa-in-slovenia",
  },
  {
    id: 29,
    name: "Sweden",
    slug: "sweden",
    flag: "🇸🇪",
    image: "/images/countries/sweden.jpg",
    visaType: "Schengen Visa",
    price: "249 AED",
    popular: false,
    region: "Schengen",
    documentPath: "/documents/required-documents-to-apply-for-a-tourist-visa-in-sweden",
  },
]
